# config.yaml
baseURL: "https://thuinanutshell.github.io"
title: "Thu Than"
theme: PaperMod

pagination:
  pagerSize: 5

params:
  defaultTheme: dark
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  ShowSocialIcons: true

  homeInfoParams:
    Title: "ğŸ‘‹ Welcome to thuinanutshell"
    Content: >
      Hi, my name is Thu. I study Data Science @ Minerva University where I got the chance to travel around the world while pursuing my degree ğŸ‘©â€ğŸ’» ğŸŒ .
      I create this blog to document my learning as an aspiring Research Engineer (or just to share some fun things I learn along the way).

  socialIcons:
    - name: github
      url: "https://github.com/thuinanutshell"
    - name: linkedin
      url: "https://www.linkedin.com/in/thu-than-2243b5315/"

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 20
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 30
    - identifier: From Scratch
      name: From Scratch
      url: /from_scratch/
      weight: 40
